services:
  - type: web
    name: maqro-backend
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_DB_URL
        sync: false
      - key: SUPABASE_USER
        sync: false
      - key: SUPABASE_PASSWORD
        sync: false
      - key: SUPABASE_HOST
        sync: false
      - key: SUPABASE_PORT
        sync: false
      - key: SUPABASE_DBNAME
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: COHERE_API_KEY
        sync: false
      - key: EMBEDDING_PROVIDER
        value: openai
      - key: EMBEDDING_MODEL
        value: text-embedding-3-small
      - key: VECTOR_STORE_TYPE
        value: pgvector
      - key: TOP_K
        value: "3"
      - key: SIMILARITY_THRESHOLD
        value: "0.7"
      - key: LOG_LEVEL
        value: INFO
      - key: WHATSAPP_ACCESS_TOKEN
        sync: false
      - key: WHATSAPP_PHONE_NUMBER_ID
        sync: false
      - key: WHATSAPP_WEBHOOK_VERIFY_TOKEN
        sync: false
      - key: WHATSAPP_APP_SECRET
        sync: false
      - key: WHATSAPP_API_VERSION
        value: v21.0 